/**
 * Archon Runtime Host — Event Envelope (ACM-001)
 *
 * Canonical event envelope emitted on every JSONL write to decisions.jsonl
 * and proposal-events.jsonl. Provides device, user, session, agent, and
 * version attribution so logs are attributable across devices/sessions.
 *
 * @see docs/specs/archon-context-model-specification.md (ACM-001)
 */

import { ARCHON_VERSION } from './version.js';

// ---------------------------------------------------------------------------
// Schema version
// ---------------------------------------------------------------------------

/**
 * Schema version for the event envelope format.
 * Increment when the envelope structure changes in a breaking way.
 */
export const SCHEMA_VERSION = 1;

// ---------------------------------------------------------------------------
// RuntimeContext
// ---------------------------------------------------------------------------

/**
 * Runtime attribution context for a single operation session.
 *
 * Captured once at process start (CLI) or app.whenReady() (desktop).
 * Injected into all event-emitting subsystems so every log entry carries
 * full attribution without repeating the lookup on each write.
 *
 * Invariant: all fields are non-empty strings. A missing field is a P0 defect.
 */
export interface RuntimeContext {
  /** Stable, machine-bound device identifier. Persisted in device.json. */
  readonly device_id: string;
  /** Stable, per-user identifier. Persisted in user.json. */
  readonly user_id: string;
  /** Per-process session identifier. Created fresh at each launch. */
  readonly session_id: string;
  /** The active project scope for this session. */
  readonly project_id: string;
  /** The operator agent acting in this session for this project. */
  readonly agent_id: string;
  /** Archon engine version at the time of the event. */
  readonly archon_version: string;
}

// ---------------------------------------------------------------------------
// EventEnvelope
// ---------------------------------------------------------------------------

/**
 * Full attribution envelope written as a single JSONL line.
 *
 * Every governance event (decision, proposal lifecycle) carries this envelope
 * so that logs can be attributed, deduplicated, and audited across devices.
 *
 * @template P - The event-type-specific payload type.
 */
export interface EventEnvelope<P = Record<string, unknown>> {
  /** 26-character ULID (deduplication key). */
  readonly event_id: string;
  /** Namespaced event type (e.g. 'governance.decision', 'proposal.created'). */
  readonly event_type: string;
  /** ISO 8601 timestamp at the moment of the event. */
  readonly timestamp: string;
  /** Archon engine version. */
  readonly archon_version: string;
  /** Stable device identifier. */
  readonly device_id: string;
  /** Stable user identifier. */
  readonly user_id: string;
  /** Per-process session identifier. */
  readonly session_id: string;
  /** Active project identifier. */
  readonly project_id: string;
  /** Operator agent identifier. */
  readonly agent_id: string;
  /** Rule snapshot hash at the time of the event. */
  readonly rs_hash: string;
  /** Schema version for forward-compatibility detection. */
  readonly schema_version: number;
  /** Event-type-specific payload. */
  readonly payload: P;
}

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

/**
 * Build a fully-attributed event envelope.
 *
 * Pure function — no I/O. Callers supply the ULID event_id so the ID
 * is generated in the calling scope (testable, deterministic).
 *
 * @param ctx - Runtime attribution context for the current session
 * @param eventId - ULID (generated by caller via ulid())
 * @param eventType - Namespaced event type string
 * @param rsHash - Rule snapshot hash at the time of the event
 * @param payload - Event-type-specific payload
 * @returns Complete EventEnvelope ready for JSON serialization
 */
export function buildEventEnvelope<P>(
  ctx: RuntimeContext,
  eventId: string,
  eventType: string,
  rsHash: string,
  payload: P,
): EventEnvelope<P> {
  return {
    event_id: eventId,
    event_type: eventType,
    timestamp: new Date().toISOString(),
    archon_version: ctx.archon_version,
    device_id: ctx.device_id,
    user_id: ctx.user_id,
    session_id: ctx.session_id,
    project_id: ctx.project_id,
    agent_id: ctx.agent_id,
    rs_hash: rsHash,
    schema_version: SCHEMA_VERSION,
    payload,
  };
}

// ---------------------------------------------------------------------------
// Test helper (exported for use in test fixtures)
// ---------------------------------------------------------------------------

/**
 * Construct a minimal, deterministic RuntimeContext for use in tests.
 *
 * All field values are fixed strings that do not depend on disk state or
 * process environment. This makes tests reproducible and I/O-free.
 *
 * MUST NOT be used in production code paths.
 */
export function makeTestContext(overrides?: Partial<RuntimeContext>): RuntimeContext {
  return {
    device_id: 'test-device-id',
    user_id: 'test-user-id',
    session_id: 'test-session-id',
    project_id: 'test-project',
    agent_id: 'test-agent-id',
    archon_version: ARCHON_VERSION,
    ...overrides,
  };
}
